ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS first_contacted_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS converted_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS negotiation_since TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS awaiting_advance_since TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS entered_awaiting_advance BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS conversion_count INTEGER DEFAULT 0;
