ALTER TABLE IF EXISTS lead_activities
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

ALTER TABLE IF EXISTS lead_notes
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

ALTER TABLE IF EXISTS lead_pricing_logs
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

ALTER TABLE IF EXISTS lead_followups
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

ALTER TABLE IF EXISTS lead_lost_reasons
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);

ALTER TABLE IF EXISTS lead_enrichment_logs
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id);
