ALTER TABLE guests ADD COLUMN IF NOT EXISTS impressions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS match_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE guests ADD COLUMN IF NOT EXISTS download_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE photos ADD COLUMN IF NOT EXISTS discovered BOOLEAN NOT NULL DEFAULT FALSE;
