-- Payroll intent-based fields

ALTER TABLE finance_transactions
  ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE employee_payouts
  ADD COLUMN IF NOT EXISTS base_salary NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS incentives NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leave_deduction NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS manual_adjustment NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carry_forward_prev NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_paid NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carry_forward_next NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS advance_next NUMERIC NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS finance_transactions_user_idx ON finance_transactions(user_id);
