ALTER TABLE projects ADD COLUMN IF NOT EXISTS slug VARCHAR(255) UNIQUE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS passcode VARCHAR(50);
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_slug ON projects(slug);
